### ISSUE TITLE
Secure Connections returning CONNECTION_NOT_SECURE

### ISSUE THREAD

**Issue by kiwisoup** [EddyVerbruggen/SSLCertificateChecker-PhoneGap-Plugin#29]
Hi,

I've tested a number of domain and fingerprint combinations and the only one that seems to work is the demo url https://build.phonegap.com. 

window.plugins.sslCertificateChecker.check(function(m) {console.log(m);}, function(m) {console.log(m);}, "https://build.phonegap.com", "2B 24 1B E0 D0 8C A6 41 68 C2 BB E3 60 0A DF 55 1A FC A8 45");

Others I have tested:

**https://github.com**
window.plugins.sslCertificateChecker.check(function(m) {console.log(m);}, function(m) {console.log(m);}, "https://github.com", "‎A0 C4 A7 46 00 ED A7 2D C0 BE CB 9A 8C B6 07 CA 58 EE 74 5E");

**https://www.google.co.nz**
window.plugins.sslCertificateChecker.check(function(m) {console.log(m);}, function(m) {console.log(m);}, "https://www.google.co.nz", "‎77 FF 51 51 BB 5F B7 16 24 53 A7 C5 5B 54 E0 AD 7F 7E 5F 66");

**https://www.grc.com**
window.plugins.sslCertificateChecker.check(function(m) {console.log(m);}, function(m) {console.log(m);}, "https://www.grc.com", "12 91 D8 D9 E4 9F 14 AB DE E3 D5 9C 42 F6 AF 61 FE F4 0E 05 D7 CC 4B 43 A0 D0 ED F7 32 B7 1B EA");

They all return "CONNECTION_NOT_SECURE" on both Android (Samsung S6 5.1.1) and iOS (iPad 9.2.1).

The test application was created in phoneGapBuild first using cli 5.2.0 and then 3.7.0.  Using version 5.0.0 of the plugin, source npm.

Any help greatly appreciated.
Steve.

**Comment by kiwisoup** [comment]
Copy and Paste Error.... d:o(

**Comment by vuhung3990** [comment]
hello, i have same issue because certificate have non-ascii character at begin, hope this will help

`static cerFingerPrint: string = "‎7A:D1:7B:AC:90:39:61:4B:57:50:1D:DC:69:87:E8:04:BC:A4:47:95".replace(/:/g, " ").replace(/[^\x00-\x7F]/g, "");`

**Comment by cmarint** [comment]
i have same issue but usin version 6.0.0.
The demo url https://build.phonegap.com work fine, but not another url's.

Any help?

Thanks
