### ISSUE TITLE
Build Failed iOS

### ISSUE THREAD

**Issue by mhubert** [EddyVerbruggen/SSLCertificateChecker-PhoneGap-Plugin#3]
Conf : Xcode Version 5.0
When I run my app, build failed with 3 error : 
 Undinined symbols for architecture armv7 
"_SetCertificateCopyData", referenced from : 
  -[SSLCertificateChecker getFingerprint:] in SSLCertificateChecker.o
"_Set<TrustGetCertificateAtIndex", referenced from : 
  -[SSLCertificateChecker connection:willSendRequestForAuthentificationChallange :] in SSLCertificateChecker.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1(use -v to see invocation)

Please how can I fixed that ?

thx.

**Comment by a568690944** [comment]
楼主同求
