### ISSUE TITLE
Adobe phonegap build 6.1 does not compile for IOS only

### ISSUE THREAD

**Issue by SingleID** [EddyVerbruggen/SSLCertificateChecker-PhoneGap-Plugin#30]
I obtain that error 

```
** BUILD FAILED **


The following build commands failed:
	CompileC build/SingleID.build/Release-iphoneos/XXXXXX.build/Objects-normal/armv7/SSLCertificateChecker.o XXXXXX/Plugins/nl.x-services.plugins.sslcertificatechecker/SSLCertificateChecker.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

with this line:
`<preference name="phonegap-version" value="cli-6.1.0" /`

But with this is all ok on IOS
`<preference name='phonegap-version' value='cli-5.2.0' />`

On android is fine any phonegap version.

**Comment by EddyVerbruggen** [comment]
Compiles just fine on my Mac with CLI 6.1.1. This is PhoneGap Build I guess? Are you using the latest version of the plugin (check the plugin command in `config.xml`)?

Also, do you have access to the full build log? As that piece of logging doesn't contain any real relevant error message.

**Comment by SingleID** [comment]
Full log from phonegap build [here](https://dl.dropboxusercontent.com/u/10636650/ssl-raw-log.txt) and I'm using the 3.3.1 version of this plugin ( the latest according to phoengap build )

nl.x-services.plugins.sslcertificatechecker    	pgb 	3.3.1 	3.3.1 	3.3.1 	android,ios

best regards

**Comment by EddyVerbruggen** [comment]
3.3.1 was released [October 2014](https://github.com/EddyVerbruggen/SSLCertificateChecker-PhoneGap-Plugin/releases), please update. Please use plugins from npm these days, they have docs on how to do it.
