### ISSUE TITLE
CONNECTION_FAILED. Details: Permission denied (missing INTERNET permission?)

### ISSUE THREAD

**Issue by lpfeup** [EddyVerbruggen/SSLCertificateChecker-PhoneGap-Plugin#31]
Hi,

I am getting the following error when using the plugin on Android :
<pre>
CONNECTION_FAILED. Details: Permission denied (missing INTERNET permission?)
</pre>

which is solved by adding the correct permission to AndroidManifest.xml :
```xml
<uses-permission android:name="android.permission.INTERNET" />
```

This should be done automatically when adding the plugin. I am creating a pull request for it.

**Comment by EddyVerbruggen** [comment]
Sounds like a pretty basic permission you'd want to add anyway, not really the responsibility of a plugin but I've merged it since it shouldn't do harm ;)

Thanks!
