### ISSUE TITLE
Always get response CONNECTION_NOT_SECURE

### ISSUE THREAD

**Issue by cakahlul** [EddyVerbruggen/SSLCertificateChecker-PhoneGap-Plugin#50]
Since i've updated my plugin to 6.0.0 version, i always get CONNECTION_NOT_SECURE. Hope you check and resolve this issue :)

**Comment by EddyVerbruggen** [comment]
Did you see the note about sha1 vs sha256 in the readme?

**Comment by PeterHdd** [comment]
@EddyVerbruggen if we go to chrome, and click on Certificate then details and scroll down, there is no sha256 fingerprint. But there is the thumbprint, do we use that or what should we do exactly?

**Comment by EddyVerbruggen** [comment]
Chrome on macOS:

<img width="499" alt="Screenshot 2019-07-03 at 13 19 34" src="https://user-images.githubusercontent.com/1426370/60587675-57309380-9d95-11e9-8a5d-d82eef43e3b2.png">
